apiVersion: v1
baseDomain: scalelab
compute:
- hyperthreading: Enabled   
  name: worker
  replicas: 8 
controlPlane:
  hyperthreading: Enabled   
  name: master 
  replicas: 3 
metadata:
  name: cloud31 
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.30.0.0/16
platform:
  none: {}
pullSecret: ''
sshKey: ''
